#
# Docker environment to use salt-ssh on windows
#
version: '2'

services:

  ct:
    # build docker image from files in this directory
    build: 
      context: ./
      dockerfile: _docker/Dockerfile
    volumes:
      - .:/app
